name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: https://registry.npmjs.org
          scope: '@kdcio'
      - name: Set GIT_USER
        run: echo '::set-env name=GIT_USER::Ian'
      - run: git config --global user.email $GIT_USER
      - name: Set GIT_EMAIL
        run: echo '::set-env name=GIT_EMAIL::ian@kdcsoftware.com'
      - run: git config --global user.name $GIT_EMAIL
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
